### ISSUE TITLE
AddressOfEntryPoint Injection still uses RWX

### ISSUE THREAD

**Issue by GuyPerson7018** [mantvydasb/RedTeaming-Tactics-and-Techniques#36]
At the page on [AddressOfEntryPoint Code Injection without VirtualAllocEx RWX](https://www.ired.team/offensive-security/code-injection-process-injection/addressofentrypoint-code-injection-without-virtualallocex-rwx), this is not really done without using RWX. As shown in the first picture, the entrypoint memory page is already under RX permissions, and as shown [here](https://www.ired.team/offensive-security/defense-evasion/finding-all-rwx-protected-memory-regions), the only reason this method works is because WriteProcessMemory is being nice and trying to change RX to RWX temporarily, which would end up creating an RWX page anyways, essentially making this technique still easily detectable by EDRs that look for RWX regions.

**Comment by mantvydasb** [comment]
Thanks, updated the page by including your comment.

**Comment by seeeeeeeeeboy** [comment]
> [在“不使用 VirtualAllocEx RWX 权限的 AddressOfEntryPoint 代码注入”](https://www.ired.team/offensive-security/code-injection-process-injection/addressofentrypoint-code-injection-without-virtualallocex-rwx)页面上，如果不使用 RWX 权限，则无法真正做到这一点。如第一张图所示，入口点内存页面已经处于 RX 权限之下，并且如此处所示[，](https://www.ired.team/offensive-security/defense-evasion/finding-all-rwx-protected-memory-regions)此方法有效的唯一原因是 WriteProcessMemory 试图将 RX 权限暂时更改为 RWX 权限，这最终还是会创建一个 RWX 页面，本质上使得这种技术仍然很容易被寻找 RWX 区域的 EDR 检测到。

hello ， boy。I tested with your code and encountered an error. ImageBase is 0x00000000
