### ISSUE TITLE
[Suggestion] Add Windows/Linux alternative to Powerview

### ISSUE THREAD

**Issue by CravateRouge** [mantvydasb/RedTeaming-Tactics-and-Techniques#39]
Hi, I'm the developer of bloodyAD. If you're interested I can add to your guides bloodyAD command lines as a Windows/Linux alternative to Powerview.

**Comment by mantvydasb** [comment]
Hey, many thanks for reaching out.

Sure, would you mind doing a pull request for review for one guide to see
how it could look like?

Mantvydas Baranauskas

ired.team - my offensive security blog
Kondencuotas Pienas
<https://open.spotify.com/artist/1XLA7hCHVBJ3H5Bnrngd2R?si=e_hxg3JKSwOCCzeFDZWLNg>
-
my music on Spotify
